# ============================================
#   SIMULATION CONFIGURATION
# ============================================

# --- Environment ---
MAP_WIDTH: 30                # Number of cells (width)
MAP_HEIGHT: 30               # Number of cells (height)
MAX_STEPS: 30               # Max steps per simulation

# --- Population ---
POP_SIZE: 100                 # Number of agents in the population
RUNS_PER_GENERATION: 10      # Independent simulations per generation


# ============================================
#   EVOLUTIONARY ALGORITHM
# ============================================

MUTATION_RATE: 0.05          # Probability of mutating a gene
MUTATION_STD: 3              # Standard deviation of Gaussian mutation
MUTATION_CLIP: 10            # Max absolute value allowed in mutation
ELITISM: 0.1                 # Proportion of best individuals preserved


# ============================================
#   VISUALIZATION
# ============================================

CELL_SIZE: 19              # Size (px) of each cell in the visualization
SCREEN_WIDTH: auto           # Window width (auto = derived from map)
SCREEN_HEIGHT: auto          # Window height (auto = derived from map)

FONDO: [150, 150, 150]            # Background color (RGB)
OBSTACLE_COLOR: [50, 50, 50]      # Obstacles color
FOOD_COLOR: [40, 130, 40]         # Food color
FONT: "Aileron-Regular.otf"       # Font for rendering text
MAX_FPS: 40                     # Max frames per second (9999 = unlimited)


# ============================================
#   EXPERIMENT / TEST SETTINGS
# ============================================

TEST: "egg_hunt"                  # Selected experiment
NETWORK_TYPE: "MLP_with_memory"   # Agent brain type

# --- Egg Hunt test ---
MIN_DISTANCE_egg: 15              # Minimum spawn distance between egg and agent

# --- Eat Them All test ---
# (parameters go here)


# ============================================
#   AGENT BRAINS
# ============================================

# --- MLP with Memory ---
MEMORY_SIZE: 0              # How many past steps the agent can remember
HIDDEN_ARCHITECTURE: []      # Hidden layers (empty list = no hidden layers)
VISION_RANGE: 1             # Vision radius (cells around agent)

# --- NEAT ---
# (parameters go here)

# --- Simple RNN ---
HIDDEN_STATE_SIZE: 15       # Size of hidden state 


# ============================================
#   MAP MANAGER / TERRAIN GENERATION
# ============================================

SCALE: 8
OCTAVES: 6
PERSITENCE: 0.5
LACUNARITY: 2.0
