name: 'Anisogamy'
description: 'With this population we want to test the evolution of anisogamy.'
author: 'CAPSA'
total_size: 30
batchs:
  batch_1:
    amount: 30
    agent_config:
      color: 'random'
      brain_config:
        brain_class: 'BasicBrain'
        inputs: 
          agent_view: [0] 
          agent_attributes: ['position']

        outputs: [[-1, 1], [0, 1], [1, 1], [-1, 0], [1, 0], [-1, -1], [0, -1], [1, -1]]

        hidden_layers_sizes: [10, 5]
        activation: 'relu'
        vision_range: 1


